### ISSUE TITLE
[Error] XMLHttpRequest 

### ISSUE THREAD

**Issue by marcelinol** [ResultadosDigitais/rdstation-js-integration#16]
Olá Luciano, tudo bem?

O Giovanni está tendo um problema com a integração dele. Você pode ajudá-lo, por favor?

Ele me encaminhou a seguinte informação:

Abaixo os erros em Safari:

[Error] Failed to load resource: Cannot make any requests from null. (contato, line 0)
[Error] XMLHttpRequest cannot load http://www.adtsys.com.br/contato/. Cannot make any requests from null. (contato, line 0)

O código usado no contact-form-7 do nosso site:
<div class="row">
<div class="col-md-9 col-md-offset-1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="result"></div>
                                </div>
                            </div><div class="form-group">
                             [text* name /50 id: name class:form-control placeholder "Nome *"]
                            </div>
                            <div class="form-group">
                                [email* email /50 id:email class:form-control placeholder "Email *"]
                            </div>
                            <div class="form-sgroup">
                                [tel* telefone 30/20 id: telefone class:form-control class:required class:digits placeholder "Telefone *"]
                            </div>
                            <div class="form-group mt15">
                               [textarea* message 3x7/300 id:comments class:form-control placeholder "Mensagem *"]
                            </div>
                            <div class="form-sgroup mt15">
                            <div class="text-center">[captchac captcha id:captcha size:g]</div>
                              [captchar captcha id:captcha-text class:form-control placeholder "Digite o texto acima"]
                            </div>
                            <div class="form-sgroup mt15">
                              [submit id:submit class:btn class:btn-glazy class:btn-orange class:btn-lg class:pull-right"Enviar"]

</div>
<div class="text-right mt30"><br>
                                <p>
                                    <small>Os campos marcados com asterisco * são obrigatorios</small>
                                </p>
                            </div>
                        </div>
</div>
<script type ='text/javascript' src="https://d335luupugsy2.cloudfront.net/js/integration/0.1.0/rd-js-integration.min.js"></script>
<script type ='text/javascript'>
    RDStationFormIntegration('3abc6003b1e3a8868eb27533f72df26f', 'site-formulario-contato');
</script>

Qualquer dúvida ou problema estou à disposição.

Abraço,

**Comment by brunogianni** [comment]
Fixed. Não ocorre mais.
