### ISSUE TITLE
Adicionar mensagens de console para facilitar a debugger e suporte aos usuários

### ISSUE THREAD

**Issue by pedrovitti** [ResultadosDigitais/rdstation-js-integration#20]
Clientes abrem tickets no suporte dizendo que a integração não está funcionando e fica difícil saber qual o problema rapidamente.

Mensagens de console facilitariam a detecção de erros e dariam mais agilidade ao suporte.

**Comment by pedrovitti** [comment]
Closed by #56. :sunglasses:

**Comment by marcelinol** [comment]
:eyes:
