### ISSUE TITLE
[Firefox] "Bloqueio" de POST 

### ISSUE THREAD

**Issue by brunogianni** [ResultadosDigitais/rdstation-js-integration#35]
Firefox tem em alguns casos bloqueado o POST a nossa API, quando usamos o post desacoplado do submit do form, isto não acontece, entretanto usando o acoplamento, não sei se devido a conflito com outros scripts, o firefox bloqueia o post e retorna as seguintes infos abaixo. Apesar das requisiçoes CORS estarem habilitadas na api, firebug retorna: Cross-Origin Request Blocked. Mesmo desabilitando o debug, a requisição não procede. 

![screen shot 2015-06-01 at 10 37 44 am](https://cloud.githubusercontent.com/assets/12086336/7914006/5e61f8e0-084a-11e5-9945-09ff68601e1a.png)
Parece que setando uma propriedade withCredentials = true isto não deveria ocorrer, entretanto deve ser investigado, visto que não sei o impacto disso:

http://stackoverflow.com/questions/25310450/cross-domain-javascript-cors-concept

O problema é que no Chrome não ocorre isso e se leads dos nossos clientes estiverem usando o firefox, pode ser que não estão chegando ao RDStation.

**Comment by ThiagoMiranda** [comment]
Opa tudo bem?
Estou fazendo a integração do script do RDstation no nosso produto e estou pegando esse erro. O estranho que mesmo com o block do firefox, o lead é enviado.  Vocês possuem alguma previsão de fix?

Obrigado
